version: '3'

services:
  traefik:
    container_name: traefik
    image: "traefik:v2.2"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - proxy
      - default
    environment:
      DOMAIN: recipebox.dev
    env_file:
      - instance/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/acme/acme.json:/etc/traefik/acme/acme.json
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.tls.certresolver=lets-encr"
      - "traefik.http.routers.traefik.tls.domains[0].main=*.${DOMAIN}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=${DOMAIN}"
      ## HTTP REDIRECT
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"  
      - "traefik.http.routers.redirect-https.entrypoints=web"
      - "traefik.http.routers.redirect-https.middlewares=redirect-to-https"

  react:
    container_name: react
    build:
      context: ./recipebox-fe/
      dockerfile: Dockerfile
    ports:
      - "1337:80"
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.react.entrypoints=websecure"
      - "traefik.http.routers.react.tls.certresolver=lets-encr"
      - "traefik.http.services.react.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

  recipebox:
    container_name: recipebox
    build:
      context: .
      dockerfile: ./setup/docker/Dockerfile
    environment:
      DOMAIN: recipebox.dev
      MONGODB_DATABASE: recipebox
      MONGODB_HOSTNAME: mongodb
    env_file:
      - instance/.env
    ports:
      - "5000:5000"
    networks:
      - proxy
      - default
    command: "gunicorn -b 0.0.0.0:5000 --reload --capture-output --log-level debug recipebox.app:app"
    volumes:
      - "./recipebox:/app/app"
      - "./tests:/app/tests"
      - "./instance:/app/instance"
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recipebox.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.recipebox.entrypoints=websecure"
      - "traefik.http.routers.recipebox.tls.certresolver=lets-encr"
      - "traefik.http.services.recipebox.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"
  
  mongodb:
    image: mongo:4.2.0
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    networks:
      - default
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
      MONGO_INITDB_DATABASE: recipebox
    env_file:
      - instance/.env
    volumes:
      - "mongodbdata:/data/db"
      - "./setup:/setup"

volumes:
  mongodbdata:

networks:
  proxy:
    external: true
  default:
    driver: bridge
