version: '3'
services:
  flask:
    container_name: recipebox
    build:
      context: .
      dockerfile: ./setup/docker/Dockerfile
    environment:
      FLASK_ENV: dev
      MONGODB_DATABASE: recipebox
      MONGODB_HOSTNAME: mongodb
    env_file:
      - instance/.env
    ports:
      - "5000:5000"
    command: "gunicorn -b 0.0.0.0:5000 --log-level=debug --reload recipebox.app:app"
    volumes:
      - "./recipebox:/app/app"
      - "./tests:/app/tests"
      - "./instance:/app/instance"
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:4.2.0
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
      MONGO_INITDB_DATABASE: recipebox
    env_file:
      - instance/.env
    volumes:
      - "mongodbdata:/data/db"

volumes:
  mongodbdata:
